-- ═══════════════════════════════════════════════════════════════════════════
-- Hair AI — hairstyles catalog seed. GENERATED — do not edit by hand.
-- Source: lib/hairstyleData.ts  ·  Regenerate: npx tsx scripts/gen-hairstyles-seed.mjs
-- Requires supabase/add-hairstyles.sql to have been run first.
-- Idempotent: upserts by id, so re-running refreshes rows without duplicating.
-- 44 styles.
-- ═══════════════════════════════════════════════════════════════════════════

insert into hairstyles
  (id, name, category, description, photos, face_shapes, hair_texture, maintenance, length, styling_time, reviews, weekly_trend)
values
  ('textured-crop', 'Textured Crop', 'Men', 'Short, choppy texture on top with a tapered or faded side, low maintenance and easy to style.', ARRAY['/styles/textured-crop/1.jpg', '/styles/textured-crop/2.jpg', '/styles/textured-crop/3.jpg']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Straight to wavy', 'Low', 'Short', '5 min', '[{"customerName":"Rahul S.","rating":5,"comment":"Clean look, barely needs styling.","daysAgo":3},{"customerName":"Vikram P.","rating":4,"comment":"Good for office, grows out nicely.","daysAgo":10}]'::jsonb, ARRAY[4, 6, 5, 8, 9, 12, 14, 16]::int[]),
  ('french-crop', 'French Crop', 'Men', 'Dense fringe cut straight across the forehead with tight sides — sharp and structured.', ARRAY['/styles/french-crop/1.jpg', '/styles/french-crop/2.jpg', '/styles/french-crop/3.jpg']::text[], ARRAY['Oval', 'Round']::text[], 'Straight, thick', 'Medium', 'Short', '8 min', '[{"customerName":"Aman K.","rating":5,"comment":"Best cut I''ve had, very sharp.","daysAgo":1}]'::jsonb, ARRAY[2, 3, 4, 4, 6, 7, 9, 11]::int[]),
  ('pompadour', 'Pompadour', 'Men', 'Volume swept up and back from the forehead, sides cut shorter for contrast.', ARRAY['/styles/pompadour/1.jpg', '/styles/pompadour/2.jpg', '/styles/pompadour/3.jpg']::text[], ARRAY['Oval', 'Heart']::text[], 'Thick, wavy', 'High', 'Medium', '12 min', '[{"customerName":"Dev R.","rating":4,"comment":"Needs daily product but looks premium.","daysAgo":6}]'::jsonb, ARRAY[6, 7, 6, 5, 4, 4, 3, 3]::int[]),
  ('slick-back-undercut', 'Slick Back Undercut', 'Men', 'Hair combed straight back with a hard contrast undercut on the sides.', ARRAY['/styles/slick-back-undercut/1.jpg', '/styles/slick-back-undercut/2.jpg', '/styles/slick-back-undercut/3.jpg']::text[], ARRAY['Oval', 'Square']::text[], 'Straight, medium', 'Medium', 'Medium', '10 min', '[]'::jsonb, ARRAY[3, 4, 5, 7, 8, 10, 9, 12]::int[]),
  ('buzz-cut', 'Buzz Cut', 'Men', 'Uniform short length all over using clippers — the lowest maintenance option.', ARRAY['/styles/buzz-cut/1.jpg', '/styles/buzz-cut/2.jpg', '/styles/buzz-cut/3.jpg']::text[], ARRAY['Oval', 'Square', 'Round']::text[], 'Any', 'Low', 'Very short', '0 min', '[{"customerName":"Sanjay M.","rating":5,"comment":"Wash and go, perfect for summer.","daysAgo":14}]'::jsonb, ARRAY[8, 9, 10, 9, 11, 13, 15, 18]::int[]),
  ('side-part', 'Classic Side Part', 'Men', 'Hair parted cleanly to one side with a defined line, timeless professional look.', ARRAY['/styles/side-part/1.jpg', '/styles/side-part/2.jpg', '/styles/side-part/3.jpg']::text[], ARRAY['Oval', 'Diamond']::text[], 'Straight', 'Medium', 'Medium', '7 min', '[]'::jsonb, ARRAY[5, 5, 4, 4, 3, 3, 2, 2]::int[]),
  ('quiff', 'Modern Quiff', 'Men', 'Volume pushed up and slightly back at the front, tapered sides for a sharp silhouette.', ARRAY['https://picsum.photos/seed/quiff-0/480/600', 'https://picsum.photos/seed/quiff-1/480/600', 'https://picsum.photos/seed/quiff-2/480/600']::text[], ARRAY['Oval', 'Heart', 'Square']::text[], 'Thick, wavy', 'Medium', 'Medium', '9 min', '[{"customerName":"Imran H.","rating":4,"comment":"Stylist nailed the height balance.","daysAgo":5}]'::jsonb, ARRAY[7, 8, 10, 11, 13, 12, 14, 17]::int[]),
  ('mullet', 'Modern Mullet', 'Men', 'Short on top and sides, length kept long at the back — bold, trend-driven cut.', ARRAY['/styles/mullet/1.jpg', '/styles/mullet/2.jpg', '/styles/mullet/3.jpg']::text[], ARRAY['Oval', 'Square']::text[], 'Straight to wavy', 'Medium', 'Long at back', '8 min', '[]'::jsonb, ARRAY[1, 2, 3, 5, 6, 8, 10, 13]::int[]),
  ('curtain-fringe', 'Curtain Fringe', 'Men', 'Center-parted fringe that falls naturally on both sides framing the face.', ARRAY['https://picsum.photos/seed/curtain-fringe-0/480/600', 'https://picsum.photos/seed/curtain-fringe-1/480/600', 'https://picsum.photos/seed/curtain-fringe-2/480/600']::text[], ARRAY['Oval', 'Round']::text[], 'Straight, medium', 'Medium', 'Medium', '6 min', '[{"customerName":"Yusuf A.","rating":3,"comment":"Nice but needs frequent trims to hold shape.","daysAgo":20}]'::jsonb, ARRAY[4, 4, 5, 4, 3, 3, 2, 2]::int[]),
  ('high-fade-afro', 'High Fade Afro', 'Men', 'Natural curl volume kept on top with a sharp high fade on the sides.', ARRAY['https://picsum.photos/seed/high-fade-afro-0/480/600', 'https://picsum.photos/seed/high-fade-afro-1/480/600', 'https://picsum.photos/seed/high-fade-afro-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round']::text[], 'Coily, dense', 'Medium', 'Short to medium', '10 min', '[]'::jsonb, ARRAY[3, 3, 4, 5, 5, 7, 8, 9]::int[]),
  ('long-layers', 'Long Layers', 'Women', 'Face-framing layers cut throughout long length for movement and volume.', ARRAY['https://picsum.photos/seed/long-layers-0/480/600', 'https://picsum.photos/seed/long-layers-1/480/600', 'https://picsum.photos/seed/long-layers-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart']::text[], 'Any', 'Medium', 'Long', '15 min', '[{"customerName":"Priya N.","rating":5,"comment":"Bounces beautifully, great recommendation.","daysAgo":4}]'::jsonb, ARRAY[9, 10, 11, 10, 12, 14, 15, 16]::int[]),
  ('bob-cut', 'Classic Bob', 'Women', 'Chin-to-shoulder length cut blunt or layered, a sharp and easy everyday style.', ARRAY['https://picsum.photos/seed/bob-cut-0/480/600', 'https://picsum.photos/seed/bob-cut-1/480/600', 'https://picsum.photos/seed/bob-cut-2/480/600']::text[], ARRAY['Oval', 'Round', 'Heart']::text[], 'Straight to wavy', 'Low', 'Short to medium', '8 min', '[{"customerName":"Anjali T.","rating":5,"comment":"Easiest style I''ve maintained, love it.","daysAgo":2}]'::jsonb, ARRAY[10, 11, 13, 12, 14, 16, 18, 20]::int[]),
  ('pixie-cut', 'Pixie Cut', 'Women', 'Very short cropped cut with textured layers on top — bold and low maintenance.', ARRAY['https://picsum.photos/seed/pixie-cut-0/480/600', 'https://picsum.photos/seed/pixie-cut-1/480/600', 'https://picsum.photos/seed/pixie-cut-2/480/600']::text[], ARRAY['Oval', 'Heart', 'Diamond']::text[], 'Any', 'Low', 'Very short', '4 min', '[]'::jsonb, ARRAY[3, 4, 4, 5, 6, 6, 7, 8]::int[]),
  ('beach-waves', 'Beach Waves', 'Women', 'Loose, tousled waves through mid-length to long hair for a relaxed natural look.', ARRAY['https://picsum.photos/seed/beach-waves-0/480/600', 'https://picsum.photos/seed/beach-waves-1/480/600', 'https://picsum.photos/seed/beach-waves-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round']::text[], 'Wavy, medium', 'Medium', 'Medium to long', '12 min', '[{"customerName":"Sneha V.","rating":4,"comment":"Great for parties, holds for hours.","daysAgo":8}]'::jsonb, ARRAY[6, 7, 8, 9, 11, 10, 12, 14]::int[]),
  ('shag-cut', 'Shag Cut', 'Unisex', 'Heavily layered, choppy cut with a textured fringe — retro-inspired and versatile.', ARRAY['https://picsum.photos/seed/shag-cut-0/480/600', 'https://picsum.photos/seed/shag-cut-1/480/600', 'https://picsum.photos/seed/shag-cut-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart']::text[], 'Wavy to curly', 'Medium', 'Medium', '10 min', '[]'::jsonb, ARRAY[2, 3, 5, 6, 8, 9, 11, 13]::int[]),
  ('crew-cut', 'Crew Cut', 'Men', 'Short, tapered cut left slightly longer at the front, graduating shorter toward the crown — clean, military-inspired and effortless.', ARRAY['https://picsum.photos/seed/crew-cut-0/480/600', 'https://picsum.photos/seed/crew-cut-1/480/600', 'https://picsum.photos/seed/crew-cut-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Straight to wavy', 'Low', 'Short', '3 min', '[{"customerName":"Arjun D.","rating":5,"comment":"Sharp and fuss-free, exactly what I wanted.","daysAgo":4}]'::jsonb, ARRAY[6, 7, 7, 9, 10, 11, 13, 15]::int[]),
  ('caesar-cut', 'Caesar Cut', 'Men', 'Short, horizontally straight fringe combed forward with even length all around — a low-effort classic that hides a receding hairline well.', ARRAY['https://picsum.photos/seed/caesar-cut-0/480/600', 'https://picsum.photos/seed/caesar-cut-1/480/600', 'https://picsum.photos/seed/caesar-cut-2/480/600']::text[], ARRAY['Oval', 'Oblong', 'Heart']::text[], 'Straight, thick', 'Low', 'Short', '4 min', '[]'::jsonb, ARRAY[3, 3, 4, 4, 5, 6, 7, 8]::int[]),
  ('ivy-league', 'Ivy League', 'Men', 'A grown-out crew cut with enough length on top to comb and part — polished, professional and easy to dress up or down.', ARRAY['https://picsum.photos/seed/ivy-league-0/480/600', 'https://picsum.photos/seed/ivy-league-1/480/600', 'https://picsum.photos/seed/ivy-league-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Straight', 'Medium', 'Short', '6 min', '[{"customerName":"Nikhil B.","rating":4,"comment":"Great smart-casual look, holds a side part well.","daysAgo":9}]'::jsonb, ARRAY[4, 5, 5, 6, 7, 7, 9, 10]::int[]),
  ('taper-fade', 'Taper Fade', 'Men', 'Gradual fade at the sideburns and neckline that keeps more length up top — a versatile base that pairs with almost any style.', ARRAY['https://picsum.photos/seed/taper-fade-0/480/600', 'https://picsum.photos/seed/taper-fade-1/480/600', 'https://picsum.photos/seed/taper-fade-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round', 'Heart']::text[], 'Any', 'Medium', 'Short to medium', '7 min', '[{"customerName":"Rohan G.","rating":5,"comment":"Clean edges, blended perfectly.","daysAgo":2}]'::jsonb, ARRAY[10, 12, 13, 14, 16, 18, 20, 23]::int[]),
  ('burst-fade', 'Burst Fade', 'Men', 'A fade that curves around the ear and tapers into the neckline, leaving length at the back — popular with mullets and mohawks.', ARRAY['https://picsum.photos/seed/burst-fade-0/480/600', 'https://picsum.photos/seed/burst-fade-1/480/600', 'https://picsum.photos/seed/burst-fade-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Straight to curly', 'Medium', 'Short to medium', '8 min', '[]'::jsonb, ARRAY[5, 6, 8, 9, 11, 13, 15, 18]::int[]),
  ('comb-over-fade', 'Comb Over Fade', 'Men', 'Longer top swept to one side over a faded side — a sharp, modern take on the traditional comb over.', ARRAY['https://picsum.photos/seed/comb-over-fade-0/480/600', 'https://picsum.photos/seed/comb-over-fade-1/480/600', 'https://picsum.photos/seed/comb-over-fade-2/480/600']::text[], ARRAY['Oval', 'Square', 'Oblong']::text[], 'Straight, medium', 'Medium', 'Medium', '9 min', '[{"customerName":"Faisal K.","rating":4,"comment":"Very corporate, looks premium with a bit of pomade.","daysAgo":12}]'::jsonb, ARRAY[7, 7, 8, 8, 9, 10, 11, 12]::int[]),
  ('disconnected-undercut', 'Disconnected Undercut', 'Men', 'Long top with no blend into the shaved sides — a bold, high-contrast look with maximum styling versatility.', ARRAY['https://picsum.photos/seed/disconnected-undercut-0/480/600', 'https://picsum.photos/seed/disconnected-undercut-1/480/600', 'https://picsum.photos/seed/disconnected-undercut-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Straight to wavy', 'High', 'Medium to long', '11 min', '[]'::jsonb, ARRAY[6, 6, 7, 7, 6, 8, 9, 10]::int[]),
  ('faux-hawk', 'Faux Hawk', 'Men', 'Hair pushed up to a soft central ridge with tapered sides — the mohawk''s wearable, work-friendly cousin.', ARRAY['https://picsum.photos/seed/faux-hawk-0/480/600', 'https://picsum.photos/seed/faux-hawk-1/480/600', 'https://picsum.photos/seed/faux-hawk-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round']::text[], 'Thick, any', 'Medium', 'Short to medium', '8 min', '[{"customerName":"Kabir S.","rating":4,"comment":"Fun without being too extreme.","daysAgo":7}]'::jsonb, ARRAY[4, 5, 5, 6, 6, 7, 8, 9]::int[]),
  ('two-block', 'Two Block Cut', 'Men', 'Volume and length kept on top with the under-sides and back clipped short — the signature Korean style, soft and youthful.', ARRAY['https://picsum.photos/seed/two-block-0/480/600', 'https://picsum.photos/seed/two-block-1/480/600', 'https://picsum.photos/seed/two-block-2/480/600']::text[], ARRAY['Oval', 'Round', 'Heart']::text[], 'Straight, medium', 'Medium', 'Medium', '9 min', '[{"customerName":"Jin H.","rating":5,"comment":"K-drama look, everyone asks where I got it.","daysAgo":3}]'::jsonb, ARRAY[8, 10, 12, 14, 15, 17, 19, 22]::int[]),
  ('man-bun', 'Man Bun', 'Men', 'Long hair gathered into a bun or top-knot, often over tapered sides — relaxed yet put-together.', ARRAY['https://picsum.photos/seed/man-bun-0/480/600', 'https://picsum.photos/seed/man-bun-1/480/600', 'https://picsum.photos/seed/man-bun-2/480/600']::text[], ARRAY['Oval', 'Square', 'Oblong']::text[], 'Straight to wavy', 'Medium', 'Long', '5 min', '[]'::jsonb, ARRAY[9, 8, 8, 7, 7, 8, 8, 9]::int[]),
  ('bro-flow', 'Bro Flow', 'Men', 'Medium-to-long hair swept straight back and left to fall naturally — an easy, grown-out look with movement.', ARRAY['https://picsum.photos/seed/bro-flow-0/480/600', 'https://picsum.photos/seed/bro-flow-1/480/600', 'https://picsum.photos/seed/bro-flow-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Wavy, medium', 'Medium', 'Medium to long', '6 min', '[{"customerName":"Sameer J.","rating":4,"comment":"Low effort but looks great after a shower shake.","daysAgo":15}]'::jsonb, ARRAY[6, 7, 8, 9, 10, 11, 12, 13]::int[]),
  ('edgar-cut', 'Edgar Cut', 'Men', 'A blunt, straight-across fringe over a high skin fade — a bold, geometric statement cut.', ARRAY['https://picsum.photos/seed/edgar-cut-0/480/600', 'https://picsum.photos/seed/edgar-cut-1/480/600', 'https://picsum.photos/seed/edgar-cut-2/480/600']::text[], ARRAY['Oval', 'Oblong', 'Diamond']::text[], 'Straight, thick', 'Medium', 'Short', '7 min', '[]'::jsonb, ARRAY[3, 4, 6, 8, 10, 12, 14, 16]::int[]),
  ('360-waves', '360 Waves', 'Men', 'Short coily hair brushed and trained into a rippling wave pattern across the whole head — a low-cut classic requiring daily brushing.', ARRAY['https://picsum.photos/seed/360-waves-0/480/600', 'https://picsum.photos/seed/360-waves-1/480/600', 'https://picsum.photos/seed/360-waves-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round']::text[], 'Coily, dense', 'High', 'Very short', '10 min', '[{"customerName":"Malik T.","rating":5,"comment":"Waves came in after a few weeks of brushing, worth it.","daysAgo":18}]'::jsonb, ARRAY[5, 5, 6, 6, 7, 7, 8, 9]::int[]),
  ('long-bob-lob', 'Long Bob (Lob)', 'Women', 'A collarbone-grazing bob — longer and softer than a classic bob, flattering on almost everyone and easy to style straight or wavy.', ARRAY['https://picsum.photos/seed/long-bob-lob-0/480/600', 'https://picsum.photos/seed/long-bob-lob-1/480/600', 'https://picsum.photos/seed/long-bob-lob-2/480/600']::text[], ARRAY['Oval', 'Round', 'Square', 'Heart']::text[], 'Any', 'Low', 'Medium', '10 min', '[{"customerName":"Meera R.","rating":5,"comment":"Perfect length — professional but still fun.","daysAgo":2}]'::jsonb, ARRAY[12, 13, 14, 15, 17, 19, 21, 24]::int[]),
  ('layered-bob', 'Layered Bob', 'Women', 'A bob with graduated internal layers for lift and movement — adds body to fine hair and softens rounder faces.', ARRAY['https://picsum.photos/seed/layered-bob-0/480/600', 'https://picsum.photos/seed/layered-bob-1/480/600', 'https://picsum.photos/seed/layered-bob-2/480/600']::text[], ARRAY['Oval', 'Round', 'Heart']::text[], 'Straight to wavy', 'Medium', 'Short to medium', '12 min', '[]'::jsonb, ARRAY[8, 9, 10, 11, 12, 13, 15, 16]::int[]),
  ('curtain-bangs', 'Curtain Bangs', 'Women', 'Soft, center-parted bangs that sweep outward to frame the face — pairs with any length and grows out gracefully.', ARRAY['https://picsum.photos/seed/curtain-bangs-0/480/600', 'https://picsum.photos/seed/curtain-bangs-1/480/600', 'https://picsum.photos/seed/curtain-bangs-2/480/600']::text[], ARRAY['Oval', 'Round', 'Square', 'Heart']::text[], 'Straight to wavy', 'Medium', 'Medium to long', '10 min', '[{"customerName":"Isha P.","rating":5,"comment":"Instantly softened my face, obsessed.","daysAgo":5}]'::jsonb, ARRAY[14, 15, 16, 18, 20, 22, 24, 27]::int[]),
  ('butterfly-cut', 'Butterfly Cut', 'Women', 'Long hair with short, face-framing layers that create a voluminous, wing-like flick — big body without losing length.', ARRAY['https://picsum.photos/seed/butterfly-cut-0/480/600', 'https://picsum.photos/seed/butterfly-cut-1/480/600', 'https://picsum.photos/seed/butterfly-cut-2/480/600']::text[], ARRAY['Oval', 'Oblong', 'Diamond']::text[], 'Wavy, medium', 'Medium', 'Long', '15 min', '[]'::jsonb, ARRAY[7, 9, 11, 13, 15, 18, 20, 23]::int[]),
  ('money-piece', 'Money Piece', 'Women', 'Two brightened, face-framing front sections that lift the complexion — a low-commitment colour accent, not a cut.', ARRAY['https://picsum.photos/seed/money-piece-0/480/600', 'https://picsum.photos/seed/money-piece-1/480/600', 'https://picsum.photos/seed/money-piece-2/480/600']::text[], ARRAY['Oval', 'Round', 'Square', 'Heart']::text[], 'Any', 'Medium', 'Medium to long', '8 min', '[{"customerName":"Tara S.","rating":4,"comment":"Brightens my face without a full colour job.","daysAgo":11}]'::jsonb, ARRAY[6, 7, 8, 8, 9, 10, 11, 12]::int[]),
  ('hime-cut', 'Hime Cut', 'Women', 'Straight, cheek-length side sections and a blunt fringe over long straight hair — a striking, geometric Japanese style.', ARRAY['https://picsum.photos/seed/hime-cut-0/480/600', 'https://picsum.photos/seed/hime-cut-1/480/600', 'https://picsum.photos/seed/hime-cut-2/480/600']::text[], ARRAY['Oval', 'Heart', 'Diamond']::text[], 'Straight, thick', 'Medium', 'Long', '12 min', '[]'::jsonb, ARRAY[3, 4, 5, 6, 7, 9, 11, 13]::int[]),
  ('curly-shag', 'Curly Shag', 'Women', 'A heavily layered shag cut for curls and coils — enhances natural definition and cuts down on frizz-prone bulk.', ARRAY['https://picsum.photos/seed/curly-shag-0/480/600', 'https://picsum.photos/seed/curly-shag-1/480/600', 'https://picsum.photos/seed/curly-shag-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart']::text[], 'Curly to coily', 'Medium', 'Medium', '13 min', '[{"customerName":"Naomi F.","rating":5,"comment":"Finally a cut that works WITH my curls.","daysAgo":6}]'::jsonb, ARRAY[5, 6, 8, 9, 11, 12, 14, 16]::int[]),
  ('blunt-cut-long', 'Blunt Cut (Long)', 'Women', 'Long hair cut to one clean, even length with no layers — makes thin hair look denser and reads sleek and modern.', ARRAY['https://picsum.photos/seed/blunt-cut-long-0/480/600', 'https://picsum.photos/seed/blunt-cut-long-1/480/600', 'https://picsum.photos/seed/blunt-cut-long-2/480/600']::text[], ARRAY['Oval', 'Round', 'Heart']::text[], 'Straight, fine to medium', 'Low', 'Long', '10 min', '[]'::jsonb, ARRAY[7, 7, 8, 8, 9, 10, 10, 11]::int[]),
  ('deva-cut', 'Deva Cut', 'Women', 'A dry-cutting technique for curly hair, shaping each curl individually for balanced, defined volume.', ARRAY['https://picsum.photos/seed/deva-cut-0/480/600', 'https://picsum.photos/seed/deva-cut-1/480/600', 'https://picsum.photos/seed/deva-cut-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart']::text[], 'Curly to coily', 'Medium', 'Medium to long', '14 min', '[{"customerName":"Layla M.","rating":4,"comment":"Curls sit so much more evenly now.","daysAgo":9}]'::jsonb, ARRAY[4, 5, 5, 6, 7, 8, 9, 10]::int[]),
  ('feathered-layers', 'Feathered Layers', 'Women', 'Soft, wispy layers feathered back and away from the face for airy movement — a retro look that''s back in rotation.', ARRAY['https://picsum.photos/seed/feathered-layers-0/480/600', 'https://picsum.photos/seed/feathered-layers-1/480/600', 'https://picsum.photos/seed/feathered-layers-2/480/600']::text[], ARRAY['Oval', 'Round', 'Square']::text[], 'Straight to wavy', 'Medium', 'Medium to long', '12 min', '[]'::jsonb, ARRAY[5, 6, 7, 8, 9, 11, 12, 14]::int[]),
  ('afro', 'Natural Afro', 'Women', 'Coily hair grown out and shaped into a rounded silhouette — celebrates natural texture with a bold, voluminous outline.', ARRAY['https://picsum.photos/seed/afro-0/480/600', 'https://picsum.photos/seed/afro-1/480/600', 'https://picsum.photos/seed/afro-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart']::text[], 'Coily, dense', 'Medium', 'Medium', '12 min', '[{"customerName":"Zara O.","rating":5,"comment":"Love the volume, so easy once picked out.","daysAgo":4}]'::jsonb, ARRAY[8, 8, 9, 10, 11, 12, 13, 15]::int[]),
  ('wolf-cut', 'Wolf Cut', 'Unisex', 'A mix of shag and mullet — choppy layers up top blending into longer, wispy lengths for an edgy, undone look.', ARRAY['https://picsum.photos/seed/wolf-cut-0/480/600', 'https://picsum.photos/seed/wolf-cut-1/480/600', 'https://picsum.photos/seed/wolf-cut-2/480/600']::text[], ARRAY['Oval', 'Square', 'Heart', 'Diamond']::text[], 'Wavy to curly', 'Medium', 'Medium', '10 min', '[{"customerName":"Alex R.","rating":5,"comment":"Trendy and low-effort, gets compliments daily.","daysAgo":3}]'::jsonb, ARRAY[9, 11, 13, 16, 18, 21, 24, 27]::int[]),
  ('box-braids', 'Box Braids', 'Unisex', 'Hair sectioned into squares and braided with or without extensions — a durable, protective style that lasts weeks.', ARRAY['https://picsum.photos/seed/box-braids-0/480/600', 'https://picsum.photos/seed/box-braids-1/480/600', 'https://picsum.photos/seed/box-braids-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round', 'Heart']::text[], 'Coily, dense', 'Low', 'Long', '180 min', '[{"customerName":"Amara D.","rating":5,"comment":"Lasted six weeks, barely any daily upkeep.","daysAgo":20}]'::jsonb, ARRAY[10, 10, 11, 12, 12, 13, 14, 15]::int[]),
  ('cornrows', 'Cornrows', 'Unisex', 'Hair braided flat to the scalp in continuous rows — a versatile protective style that can form intricate patterns.', ARRAY['https://picsum.photos/seed/cornrows-0/480/600', 'https://picsum.photos/seed/cornrows-1/480/600', 'https://picsum.photos/seed/cornrows-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round', 'Oblong']::text[], 'Coily, dense', 'Low', 'Any', '120 min', '[]'::jsonb, ARRAY[7, 7, 8, 8, 9, 10, 11, 12]::int[]),
  ('dreadlocks', 'Dreadlocks', 'Unisex', 'Hair rope-like sections formed by matting and locking over time — a long-term, low-daily-maintenance commitment.', ARRAY['https://picsum.photos/seed/dreadlocks-0/480/600', 'https://picsum.photos/seed/dreadlocks-1/480/600', 'https://picsum.photos/seed/dreadlocks-2/480/600']::text[], ARRAY['Oval', 'Square', 'Diamond']::text[], 'Coily to curly', 'Medium', 'Medium to long', '15 min', '[{"customerName":"Kai N.","rating":4,"comment":"Takes patience to mature but worth it.","daysAgo":30}]'::jsonb, ARRAY[6, 6, 6, 7, 7, 8, 8, 9]::int[]),
  ('cropped-taper', 'Cropped Taper', 'Unisex', 'A short, uniform crop with lightly tapered edges — gender-neutral, wash-and-go, and flattering on most face shapes.', ARRAY['https://picsum.photos/seed/cropped-taper-0/480/600', 'https://picsum.photos/seed/cropped-taper-1/480/600', 'https://picsum.photos/seed/cropped-taper-2/480/600']::text[], ARRAY['Oval', 'Square', 'Round', 'Heart']::text[], 'Any', 'Low', 'Short', '3 min', '[]'::jsonb, ARRAY[5, 6, 6, 7, 8, 9, 10, 11]::int[])
on conflict (id) do update set
  name         = excluded.name,
  category     = excluded.category,
  description  = excluded.description,
  photos       = excluded.photos,
  face_shapes  = excluded.face_shapes,
  hair_texture = excluded.hair_texture,
  maintenance  = excluded.maintenance,
  length       = excluded.length,
  styling_time = excluded.styling_time,
  reviews      = excluded.reviews,
  weekly_trend = excluded.weekly_trend,
  updated_at   = now();
